"""Deterministic plan builders for fast, common Excel requests."""

from __future__ import annotations

import re
import uuid

from core.actions.adapters.excel.capabilities import ADD_CHART, CREATE_TABLE
from core.actions.adapters.excel.snapshot import ExcelSnapshot
from core.actions.contracts import ActionOperation, ActionPlan, ActionRisk


def build_table_chart_plan(
    snapshot: ExcelSnapshot,
    *,
    include_chart: bool = True,
    chart_kind: str = "column",
    chart_title: str = "",
) -> ActionPlan:
    """Build the first fast path without requiring a second model call."""
    table_name = _available_name("WispTable", snapshot.table_names)
    operations = [
        ActionOperation(
            id="create_table",
            type=CREATE_TABLE,
            args={
                "range": snapshot.selection_address,
                "name": table_name,
                "has_headers": True,
            },
        )
    ]
    if include_chart:
        operations.append(
            ActionOperation(
                id="add_chart",
                type=ADD_CHART,
                args={
                    "source": table_name,
                    "name": _available_name("WispChart", snapshot.chart_names),
                    "kind": chart_kind,
                    "title": chart_title or "Chart from selected data",
                },
                depends_on=("create_table",),
            )
        )
    summary = "Turn the selected range into a table"
    if include_chart:
        summary += f" and add a {chart_kind} chart"
    return ActionPlan(
        plan_id=uuid.uuid4().hex,
        app="excel",
        target=snapshot.target,
        summary=summary,
        operations=tuple(operations),
        risk=ActionRisk.MEDIUM,
        requires_confirmation=True,
    )


def _available_name(prefix: str, existing_names: tuple[str, ...]) -> str:
    """Return a stable Excel object name that is not already in use."""
    existing = {name.casefold() for name in existing_names}
    if prefix.casefold() not in existing:
        return prefix
    index = 2
    while f"{prefix}{index}".casefold() in existing:
        index += 1
    return f"{prefix}{index}"


def valid_excel_object_name(name: str) -> bool:
    """Conservatively accept safe table/chart names generated by Wisp."""
    return bool(re.fullmatch(r"[A-Za-z_][A-Za-z0-9_.]{0,254}", name))
